name: Caching Dependencies Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-cache:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository's code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the cache
      - name: Cache dependencies
        id: cache-step # Give this step an ID to reference its output
        uses: actions/cache@v4
        with:
          # A path to cache. We'll use a dummy path since we aren't installing anything.
          path: ~/.cache/dummy
          # The key for the cache, as required by the quiz
          key: ${{ runner.os }}-cache-387cb92

      # Step 3: The required step that echoes the cache hit/miss result
      - name: prime-cache-387cb92
        run: |
          echo "Cache hit status: ${{ steps.cache-step.outputs.cache-hit }}"
