name: Simple Caching Workflow

on:
  workflow_dispatch:

jobs:
  caching-job:
    runs-on: ubuntu-latest
    steps:
      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ./cache-path
          key: cache-387cb92

      - name: prime-cache-387cb92
        run: |
          echo "Cache hit status: ${{ steps.cache-step.outputs.cache-hit }}"
